- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-20230202101855159100000010.ccrbwr8h4cgh.us-west-2.rds.amazonaws.com"
    login_user: "michael"
    login_password: "michaeloajala"
    name: toolingdb
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Input tooling credentials
  ansible.builtin.replace:
    path: /var/www/html/functions.php
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^mysql.tooling.svc.cluster.local', line: "terraform-20230202101855159100000010.ccrbwr8h4cgh.us-west-2.rds.amazonaws.com" }
    - { regexp: '^admin', line: "michael" }
    - { regexp: '^tooling', line: "toolingdb" }
    - { regexp: '^admin', line: "michaeloajala" }
